#!/bin/python3

import math
import os
import random
import re
import sys

def camelcase(s):
    count=0
    for ch in s:
        if ch.isupper()==True:
            count+=1
    return count+1        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = camelcase(s)

    fptr.write(str(result) + '\n')

    fptr.close()
