#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the marsExploration function below.
def marsExploration(s):
    val=len(s)//3
    st="SOS"
    st=st*val
    count=0
    for index in range(0,len(st)):
        for i in range(index,len(s)):
            if st[index]==s[i]:
                
                break 
            else:
                count+=1
                break
    return count                    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
