#!/bin/python3

import math
import os
import random
import re
import sys


def superReducedString(s):
    res = []
    for c in s:
        if res and res[-1] == c: "if list res is not empty and last element is equal c"
            res.pop()
        else:
            res.append(c)
    res = ''.join(res)
    if len(res)!=0:
        return res
    else:
        return "Empty String"

                    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
